"""
Generate word-grouped caption clips for a HyperFrames composition from a
word-level ASR transcript (ElevenLabs Scribe JSON format).

- Groups 1-3 words per phrase.
- Breaks on sentence punctuation, on long gaps (>= 320ms), or on max words.
- Skips the hook window so the hero caption block can own the frame.
- Each phrase emitted as a <div class="clip running-caption"> with timing.
- Optional BRAND_MERGES for multi-token brand names (e.g. "Higgs Field" → "Higgsfield").
- Optional TOKEN_REPLACE for single-token fixes (phonetic ASR mistakes, censorship).

Usage:
  python generate_captions.py \\
      --transcript /path/to/edit/transcripts/source.tight.json \\
      --out /path/to/edit/captions_generated.html \\
      --hook-end 3.50

The output HTML can be pasted directly into the composition's <div id="root">.
"""

from __future__ import annotations

import argparse
import html
import json
import sys
from pathlib import Path

MAX_WORDS = 3
GAP_BREAK = 0.320          # seconds — break a phrase if intra-word gap >= this
SENTENCE_PUNCT = {".", "!", "?"}
SOFT_PUNCT = {",", ":", ";", "—"}
PAD_BEFORE = 0.06          # seconds before first word's start
PAD_AFTER = 0.12           # seconds after last word's end


# Multi-token brand names that read better as one caption token.
# Add your own — case-sensitive on first token, strip punctuation from comparison.
BRAND_MERGES: list[tuple[list[str], str]] = [
    (["Higgs", "Field"], "Higgsfield"),
    # (["Open", "AI"], "OpenAI"),
    # (["You", "Tube"], "YouTube"),
]


# Single-token text replacements (case-sensitive).
# Applied after merges. Used for phonetic mis-transcriptions and on-screen censorship.
TOKEN_REPLACE: dict[str, str] = {
    # On-screen censorship for platform-safe captions
    "fuck": "f***",
    "Fuck": "F***",
    "shit": "s***",
    "Shit": "S***",
    # Add your own brand-specific phonetic fixes here:
    # "RooFlow": "RuFlo",
}


def _merge_brand_terms(words: list[dict]) -> list[dict]:
    """Collapse known multi-token brand names into single virtual words."""
    out: list[dict] = []
    i = 0
    while i < len(words):
        merged = None
        for tokens, replacement in BRAND_MERGES:
            n = len(tokens)
            if i + n <= len(words):
                window = [words[i + k]["text"].strip().rstrip(",.!?:;") for k in range(n)]
                if window == tokens:
                    last_raw = words[i + n - 1]["text"].strip()
                    trail = ""
                    for ch in reversed(last_raw):
                        if ch in ",.!?:;":
                            trail = ch + trail
                        else:
                            break
                    merged = {
                        "text": replacement + trail,
                        "start": words[i]["start"],
                        "end": words[i + n - 1]["end"],
                        "type": "word",
                    }
                    i += n
                    break
        if merged is not None:
            out.append(merged)
        else:
            out.append(words[i])
            i += 1
    return out


def load_words(path: Path) -> list[dict]:
    data = json.loads(path.read_text(encoding="utf-8"))
    words = [w for w in data["words"] if w.get("type") == "word"]
    merged = _merge_brand_terms(words)
    for w in merged:
        raw = w["text"].strip()
        base = raw.rstrip(",.!?:;")
        trail = raw[len(base):]
        if base in TOKEN_REPLACE:
            w["text"] = TOKEN_REPLACE[base] + trail
    return merged


def group_words(words: list[dict]) -> list[dict]:
    """Return phrases: [{start, end, text}, ...]"""
    phrases: list[dict] = []
    buf: list[dict] = []
    for i, w in enumerate(words):
        buf.append(w)
        flush = False
        text = w["text"].strip()
        ends_sentence = bool(text) and text[-1] in SENTENCE_PUNCT
        ends_soft = bool(text) and text[-1] in SOFT_PUNCT

        if len(buf) >= MAX_WORDS:
            flush = True
        elif ends_sentence:
            flush = True
        elif ends_soft and len(buf) >= 2:
            flush = True
        elif i + 1 < len(words):
            gap = words[i + 1]["start"] - w["end"]
            if gap >= GAP_BREAK and len(buf) >= 1:
                flush = True

        if flush:
            phrases.append(_phrase_from(buf))
            buf = []

    if buf:
        phrases.append(_phrase_from(buf))
    return phrases


def _phrase_from(buf: list[dict]) -> dict:
    text = " ".join(w["text"].strip(" ").rstrip(",.!?:;") for w in buf)
    return {
        "start": buf[0]["start"],
        "end": buf[-1]["end"],
        "text": text.strip(),
    }


def emit_html(phrases: list[dict], hook_end: float) -> str:
    lines = []
    lines.append("<!-- AUTO-GENERATED by generate_captions.py — do not hand-edit -->")
    gap = 0.02  # forced gap between consecutive captions on the same track
    floor = hook_end + gap
    out_clips = []
    for i, p in enumerate(phrases):
        if 0.0 <= p["start"] < hook_end:
            continue  # skip — hero hook caption owns this window
        raw_start = max(floor, p["start"] - PAD_BEFORE)
        raw_end = p["end"] + PAD_AFTER
        if out_clips:
            last = out_clips[-1]
            raw_start = max(raw_start, last["end"] + gap)
        # Clip end so it does not overlap the next phrase's start
        for j in range(i + 1, len(phrases)):
            nxt = phrases[j]
            if hook_end <= nxt["start"]:
                next_start = max(floor, nxt["start"] - PAD_BEFORE)
                raw_end = min(raw_end, next_start - gap)
                break
        duration = max(0.1, round(raw_end - raw_start, 3))
        start = round(raw_start, 3)
        out_clips.append({"start": start, "end": start + duration, "duration": duration, "text": p["text"]})

    for i, c in enumerate(out_clips):
        safe = html.escape(c["text"])
        lines.append(
            f'<div id="cap-{i:03d}" class="clip running-caption" '
            f'data-start="{c["start"]}" data-duration="{c["duration"]}" data-track-index="10">'
            f"{safe}</div>"
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--transcript", required=True, help="Path to the tight transcript JSON.")
    ap.add_argument("--out", required=True, help="Path where the generated HTML caption block will be written.")
    ap.add_argument("--hook-end", type=float, default=3.50, help="Seconds — anything before this is the hook window and gets skipped from running captions (default 3.50).")
    args = ap.parse_args()

    transcript_path = Path(args.transcript).resolve()
    out_path = Path(args.out).resolve()

    if not transcript_path.exists():
        print(f"ERROR: transcript not found: {transcript_path}", file=sys.stderr)
        sys.exit(1)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    words = load_words(transcript_path)
    phrases = group_words(words)
    out_path.write_text(emit_html(phrases, args.hook_end), encoding="utf-8")
    kept = sum(1 for p in phrases if p["start"] >= args.hook_end)
    skipped = len(phrases) - kept
    print(f"Wrote {kept} caption clips (skipped {skipped} in hook window) → {out_path}")


if __name__ == "__main__":
    main()
